/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cheque.print;

import java.awt.Toolkit;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author DELL
 */
public class Progress extends javax.swing.JFrame {

    /**
     * Creates new form Progress
     */
    public Progress() {
        initComponents();
        progressbar();
        loading();
//         this.setIconImage(new ImageIcon(getClass().getResource("infologoo.png")).getImage());
    }


    void loading() {
        final String N = "Loading...";
        new Thread(new Runnable() {

            @Override
            public void run() {
                int i;
                for (i = 0; i <= N.length(); i++) {
                    jLabel3.setText(N.substring(0, i));
                    if (i == 10) {
                        jLabel3.setText("");
                        i = 0;
                    }
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException e) {
                        System.out.println(e);
                    }
                }

            }
        }).start();

    }

    void progressbar() {

        new Thread(new Runnable() {
            @SuppressWarnings("empty-statement")
            @Override
            public void run() {
                int i = 0;
                for (i = 0; i <= 100; i++) {

                    jProgressBar1.setValue(i);
                    try {
                        Thread.sleep(100);
                    } catch (Exception e) {
                    }
                    if (i >= 0 && i <= 10) {
                        jLabel2.setText("Conecting To The Main Server...");

                    }
                    if (i >= 11 && i <= 20) {
                        jLabel2.setText("Conecting To The Main Server......");

                    }
                    if (i >= 21 && i <= 30) {
                        jLabel2.setText("Conecting To The Main Server...");

                    }

                    if (i >= 31 && i <= 40) {
                        jLabel2.setText("Loading Database...");

                    }
                    if (i >= 41 && i <= 50) {
                        jLabel2.setText("Loading Database.......");

                    }
                    if (i >= 51 && i <= 60) {
                        jLabel2.setText("Loading Done...");

                    }
                    if (i >= 61 && i <= 70) {
                        jLabel2.setText("Please Wait...");

                    }
                    if (i >= 71 && i <= 80) {
                        jLabel2.setText("Please Wait......");

                    }
                    if (i >= 81 && i <= 85) {
                        jLabel2.setText("Thank You For Join With Our Systems...");

                    }
                    if (i >= 86 && i <= 90) {
                        jLabel2.setText("Thank You For Join With Our Systems.....");

                    }
                    if (i == 100) {

                        Toolkit.getDefaultToolkit().beep();
m();
                    }

                }

            }
        }).start();
        

    }

    void m() {
        this.dispose();

        new login().setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Start");
        setBackground(new java.awt.Color(204, 0, 204));
        setForeground(new java.awt.Color(255, 0, 255));
        setUndecorated(true);
        setOpacity(0.9F);
        setResizable(false);

        jProgressBar1.setForeground(new java.awt.Color(0, 255, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Progress");

        jLabel3.setForeground(new java.awt.Color(0, 165, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)))
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(455, 298));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Progress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Progress().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
